module.exports = {
     data_member: [
          {
               name: 'Wahyu Saputra',
               nickName: 'Wahyu',
               address: 'A1 No. 11',
               position: 'Ketua',
               img: 'https://i.ibb.co/KjGs4PR/Wahyu.jpg',
               email: '-',
               phone: '082297777934',
               group: 'Pengurus Inti',
               order: 0,
          },
          {
               name: 'Gugun',
               nickName: 'Ugun',
               address: 'I2 No. 09',
               position: 'Wakil Ketua',
               img: 'https://i.ibb.co/XXSgwBS/Ugun-Merdekawati.jpg',
               email: 'ugunmerdekawati@gmail.com',
               phone: '082121144675',
               group: 'Pengurus Inti',
               order: 0,
          },
          {
               name: 'Arif Budiman, M.Sn',
               nickName: 'Nino',
               address: 'J2 No. 18',
               position: 'Sekretaris',
               img: 'https://i.ibb.co/C6gRpND/Nino.jpg',
               email: 'Afrannino@gmail.com',
               phone: '0811233092',
               group: 'Pengurus Inti',
               order: 0,
          },
          {
               name: 'Andi Setiandi',
               nickName: 'Andi',
               address: 'B3 No. 02',
               position: 'Bendahara',
               img: 'https://i.ibb.co/G0zPX2f/Andi-Setiandi.jpg',
               email: 'andysetiandi@gmail.com',
               phone: '08986511319',
               group: 'Pengurus Inti',
               order: 0,
          },
          {
               name: 'Asep Gunadi',
               nickName: 'Hawhaw',
               address: 'B3 No. 04',
               position: 'Koordinator Blok 1 (A-B)',
               img: 'https://i.ibb.co/JnCwpQL/si-Hawhaw.jpg',
               email: 'asepsigunadi27@gmail.com',
               phone: '085722683255',
               group: 'Struktural',
               order: 1,
          },
          {
               name: 'Hamdan Patra Alam',
               nickName: 'Patra',
               address: 'C2 No. 10 ',
               email: 'patraalam@gmail.com',
               phone: '08112348678',
               position: 'Koordinator Blok 2 (C-D)',
               img: 'https://i.ibb.co/BnQccZB/hamdan-patra-alam.jpg',
               group: 'Struktural',
               order: 1,
          },
          {
               name: 'Luck.y Nugraha',
               nickName: 'Uky',
               address: 'E2 No. 02',
               position: 'Koordinator Blok 3 (E-F)',
               img: 'https://i.ibb.co/pwPgkVj/Lucky-Nugraha.jpg',
               email: 'luckynugraha94@gmail.com',
               phone: '08978425093',
               group: 'Struktural',
               order: 1,
          },
          {
               name: 'Dika Rachman, S.Pd',
               nickName: 'Dika',
               phone: '08986063135',
               email: 'dika.rachman8@gmail.com',
               address: 'H1 No. 14',
               position: 'Koordinator Keagamaan',
               img: 'https://i.ibb.co/Wx6bSHc/dika-rachman.jpg',
               group: 'Fungsional (Badan Kelengkapan)',
               order: 2,
          },
          {
               name: 'Rangga Darmajati',
               nickName: 'Rangga',
               address: 'G2 No. 03',
               position: 'Koordinator Blok 4 (G-H)',
               img: 'https://i.ibb.co/82M7KWM/Rangga-Darmajati.jpg',
               email: 'rangga.android69@gmail.com',
               phone: '085171072640/ 085721731478',
               group: 'Struktural',
               order: 1,
          },
          {
               name: 'Ahmad Rahmadi',
               nickName: 'Ahmad',
               address: 'C3 No. 10',
               position: 'Hubungan Masyarakat',
               img: 'https://i.ibb.co/jfFKBL0/Ahmad-Rahmadi.jpg',
               email: 'rahmadiahmad87@gmail.com',
               phone: '085659586958',
               group: 'Fungsional (Badan Kelengkapan)',
               order: 2,
          },
          {
               name: 'Nona Anandha Diningrat',
               nickName: 'Nona',
               address: 'C1 No. 11',
               position: 'Hubungan Masyarakat',
               img: 'https://i.ibb.co/DMqdBwt/Nona-Anandha-Diningrat.jpg',
               email: 'nonaanandhadiningrat@gmail.com',
               phone: '081220102205',
               group: 'Fungsional (Badan Kelengkapan)',
               order: 2,
          },
          {
               name: 'Sigit Baihaqi',
               nickName: 'Sigit',
               email: 'sigitbaihaqi13@gmail.com',
               phone: '088809492922',
               address: 'H1 No. 18',
               position: 'Perencanaan dan Pengembangan Masyarakat',
               img: 'https://i.ibb.co/jTCLrkd/SIGIT-BAIHAQI.jpg',
               group: 'Fungsional (Badan Kelengkapan)',
               order: 2,
          },
          {
               name: 'Nendar Kusnadi',
               nickName: 'Nday',
               address: 'I4 No. 05',
               position: 'Perencanaan dan Pengembangan Masyarakat',
               img: 'https://i.ibb.co/dG2gLVC/NDAY-KACAPI.jpg',
               email: 'ndaynendar15@gmail.com',
               phone: '085860823433',
               group: 'Fungsional (Badan Kelengkapan)',
               order: 2,
          },
          {
               name: 'Rimba Igustira',
               nickName: 'Rimba',
               address: 'B4 No. 10',
               email: 'rimbaigustira90@gmail.com',
               phone: '085794989817',
               position: 'Keamanan, Ketertiban dan Kebersihan',
               group: 'Fungsional (Badan Kelengkapan)',
               img: 'https://i.ibb.co/M6Qqxg0/Rimba.jpg'
          },
          {
               name: 'Suyudi Yudi',
               nickName: 'Yudi',
               address: 'E2 No. 07',
               position: 'Keamanan, Ketertiban dan Kebersihan',
               img: 'https://i.ibb.co/yY2z8bK/Suyudi-Yudi.jpg',
               email: 'suyudiyudi372@gmail.com',
               phone: '081546807707',
               group: 'Fungsional (Badan Kelengkapan)',
               order: 2,
          },
          {
               name: 'Mohamad Fahrul Azis, S.M.',
               nickName: 'Fahzis',
               address: 'D2 No. 03',
               position: 'Media dan Teknologi Informasi',
               img: 'https://i.ibb.co/MVdBzdQ/Mohamad-Fahrul-Azis.jpg',
               email: 'mfahrulazis3@gmail.com',
               phone: '085157569929',
               group: 'Fungsional (Badan Kelengkapan)',
               order: 2,
          },
          {
               name: 'Wisnu Adi Wardhana',
               nickName: 'Ciwun',
               address: 'B5 No. 21',
               position: 'Media dan Teknologi Informasi',
               img: 'https://i.ibb.co/ssc6qPZ/Wisnu-Wardhana.jpg',
               email: 'adiwardhanawisnu@gmail.com',
               phone: '081298698252',
               group: 'Fungsional (Badan Kelengkapan)',
               order: 2,
          },
          {
               name: 'Florent Reno Eleganta',
               nickName: 'Reno Gembok',
               address: 'D2 No. 03',
               position: 'Koordinator Blok 5 (I-J)',
               img: 'https://i.ibb.co/WGcCMGp/Florent-Reno-Eleganta.jpg',
               email: 'renoeleganta@gmail.com',
               phone: '081239604874',
               group: 'Struktural',
               order: 1,

          },
          {
               name: 'Ahmad Zakky Askarudin',
               nickName: 'Zakky',
               address: 'B4 No. 04',
               position: 'Keagamaan, Kesehatan, dan Kesejahteraan sosial',
               img: 'https://i.ibb.co/n1R7DgZ/Zaki.jpg',
               email: 'ahmadzakky90@gmail.com',
               phone: '083820416980',
               group: 'Fungsional (Badan Kelengkapan)',
               order: 2,
          },

     ]
}